// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkbldtaiggnfmuffnwvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprYmxkdGFpZ2duZm11ZmZud3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDA5MTgsImV4cCI6MjA2NDQ3NjkxOH0.xfXA3JHI4yEx2CgwfBakgvMDwgxMU0aEnnyJcHiobpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);